=== AntAndriy7/GitJava/Lab7/7_1/resources/department.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Department" type="DepartmentType"/>
    <xs:complexType name="DepartmentType">
        <xs:sequence>
            <xs:element name="company" type="companyType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="companyType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="year_founded" type="xs:int"/>
            <xs:element name="employees" type="employeesType"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="employeeType">
        <xs:sequence>
            <xs:element name="full_name" type="xs:string"/>
            <xs:element name="age" type="xs:int"/>
            <xs:element name="salary" type="xs:double"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="employeesType">
        <xs:sequence>
            <xs:element name="employee" type="employeeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== AntAndriy7/GitJava/Lab7/7_1/resources/department.xml
<?xml version="1.0" encoding="UTF-8"?>
<Department xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="department.xsd">
    <company ID="Com001">
        <name>Company A</name>
        <year_founded>2000</year_founded>
        <employees>
            <employee ID="Emp001">
                <full_name>John Smith</full_name>
                <age>30</age>
                <salary>50000.0</salary>
            </employee>
            <employee ID="Emp002">
                <full_name>Sophia Garcia</full_name>
                <age>25</age>
                <salary>45000.0</salary>
            </employee>
        </employees>
    </company>
    <company ID="Com002">
        <name>Company B</name>
        <year_founded>1995</year_founded>
        <employees>
            <employee ID="Emp003">
                <full_name>Bob Miller</full_name>
                <age>40</age>
                <salary>60000.0</salary>
            </employee>
        </employees>
    </company>
    <company ID="Com003">
        <name>Company C</name>
        <year_founded>1997</year_founded>
        <employees>
            <employee ID="Emp004">
                <full_name>Mia Rodriguez</full_name>
                <age>32</age>
                <salary>75000.0</salary>
            </employee>
        </employees>
    </company>
</Department>
